# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dys/new/TOMS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dys/new/TOMS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dys/new/TOMS/CMakeFiles /home/dys/new/TOMS//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dys/new/TOMS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gastask

# Build rule for target.
gastask: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gastask
.PHONY : gastask

# fast build rule for target.
gastask/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/build
.PHONY : gastask/fast

#=============================================================================
# Target rules for targets named gasgen

# Build rule for target.
gasgen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gasgen
.PHONY : gasgen

# fast build rule for target.
gasgen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/build
.PHONY : gasgen/fast

dynamic_resource_generators/gen_netcommander.o: dynamic_resource_generators/gen_netcommander.c.o
.PHONY : dynamic_resource_generators/gen_netcommander.o

# target to build an object file
dynamic_resource_generators/gen_netcommander.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/dynamic_resource_generators/gen_netcommander.c.o
.PHONY : dynamic_resource_generators/gen_netcommander.c.o

dynamic_resource_generators/gen_netcommander.i: dynamic_resource_generators/gen_netcommander.c.i
.PHONY : dynamic_resource_generators/gen_netcommander.i

# target to preprocess a source file
dynamic_resource_generators/gen_netcommander.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/dynamic_resource_generators/gen_netcommander.c.i
.PHONY : dynamic_resource_generators/gen_netcommander.c.i

dynamic_resource_generators/gen_netcommander.s: dynamic_resource_generators/gen_netcommander.c.s
.PHONY : dynamic_resource_generators/gen_netcommander.s

# target to generate assembly for a file
dynamic_resource_generators/gen_netcommander.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/dynamic_resource_generators/gen_netcommander.c.s
.PHONY : dynamic_resource_generators/gen_netcommander.c.s

dynamic_resource_generators/gen_network.o: dynamic_resource_generators/gen_network.c.o
.PHONY : dynamic_resource_generators/gen_network.o

# target to build an object file
dynamic_resource_generators/gen_network.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/dynamic_resource_generators/gen_network.c.o
.PHONY : dynamic_resource_generators/gen_network.c.o

dynamic_resource_generators/gen_network.i: dynamic_resource_generators/gen_network.c.i
.PHONY : dynamic_resource_generators/gen_network.i

# target to preprocess a source file
dynamic_resource_generators/gen_network.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/dynamic_resource_generators/gen_network.c.i
.PHONY : dynamic_resource_generators/gen_network.c.i

dynamic_resource_generators/gen_network.s: dynamic_resource_generators/gen_network.c.s
.PHONY : dynamic_resource_generators/gen_network.s

# target to generate assembly for a file
dynamic_resource_generators/gen_network.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/dynamic_resource_generators/gen_network.c.s
.PHONY : dynamic_resource_generators/gen_network.c.s

dynamic_resource_generators/gen_task.o: dynamic_resource_generators/gen_task.c.o
.PHONY : dynamic_resource_generators/gen_task.o

# target to build an object file
dynamic_resource_generators/gen_task.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/dynamic_resource_generators/gen_task.c.o
.PHONY : dynamic_resource_generators/gen_task.c.o

dynamic_resource_generators/gen_task.i: dynamic_resource_generators/gen_task.c.i
.PHONY : dynamic_resource_generators/gen_task.i

# target to preprocess a source file
dynamic_resource_generators/gen_task.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/dynamic_resource_generators/gen_task.c.i
.PHONY : dynamic_resource_generators/gen_task.c.i

dynamic_resource_generators/gen_task.s: dynamic_resource_generators/gen_task.c.s
.PHONY : dynamic_resource_generators/gen_task.s

# target to generate assembly for a file
dynamic_resource_generators/gen_task.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/dynamic_resource_generators/gen_task.c.s
.PHONY : dynamic_resource_generators/gen_task.c.s

gen_task_src/GA.o: gen_task_src/GA.c.o
.PHONY : gen_task_src/GA.o

# target to build an object file
gen_task_src/GA.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/gen_task_src/GA.c.o
.PHONY : gen_task_src/GA.c.o

gen_task_src/GA.i: gen_task_src/GA.c.i
.PHONY : gen_task_src/GA.i

# target to preprocess a source file
gen_task_src/GA.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/gen_task_src/GA.c.i
.PHONY : gen_task_src/GA.c.i

gen_task_src/GA.s: gen_task_src/GA.c.s
.PHONY : gen_task_src/GA.s

# target to generate assembly for a file
gen_task_src/GA.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/gen_task_src/GA.c.s
.PHONY : gen_task_src/GA.c.s

gen_task_src/gasgen.o: gen_task_src/gasgen.c.o
.PHONY : gen_task_src/gasgen.o

# target to build an object file
gen_task_src/gasgen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/gen_task_src/gasgen.c.o
.PHONY : gen_task_src/gasgen.c.o

gen_task_src/gasgen.i: gen_task_src/gasgen.c.i
.PHONY : gen_task_src/gasgen.i

# target to preprocess a source file
gen_task_src/gasgen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/gen_task_src/gasgen.c.i
.PHONY : gen_task_src/gasgen.c.i

gen_task_src/gasgen.s: gen_task_src/gasgen.c.s
.PHONY : gen_task_src/gasgen.s

# target to generate assembly for a file
gen_task_src/gasgen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/gen_task_src/gasgen.c.s
.PHONY : gen_task_src/gasgen.c.s

gen_task_src/gastask.o: gen_task_src/gastask.c.o
.PHONY : gen_task_src/gastask.o

# target to build an object file
gen_task_src/gastask.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/gen_task_src/gastask.c.o
.PHONY : gen_task_src/gastask.c.o

gen_task_src/gastask.i: gen_task_src/gastask.c.i
.PHONY : gen_task_src/gastask.i

# target to preprocess a source file
gen_task_src/gastask.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/gen_task_src/gastask.c.i
.PHONY : gen_task_src/gastask.c.i

gen_task_src/gastask.s: gen_task_src/gastask.c.s
.PHONY : gen_task_src/gastask.s

# target to generate assembly for a file
gen_task_src/gastask.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/gen_task_src/gastask.c.s
.PHONY : gen_task_src/gastask.c.s

gen_task_src/report.o: gen_task_src/report.c.o
.PHONY : gen_task_src/report.o

# target to build an object file
gen_task_src/report.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/gen_task_src/report.c.o
.PHONY : gen_task_src/report.c.o

gen_task_src/report.i: gen_task_src/report.c.i
.PHONY : gen_task_src/report.i

# target to preprocess a source file
gen_task_src/report.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/gen_task_src/report.c.i
.PHONY : gen_task_src/report.c.i

gen_task_src/report.s: gen_task_src/report.c.s
.PHONY : gen_task_src/report.s

# target to generate assembly for a file
gen_task_src/report.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/gen_task_src/report.c.s
.PHONY : gen_task_src/report.c.s

gen_task_src/task.o: gen_task_src/task.c.o
.PHONY : gen_task_src/task.o

# target to build an object file
gen_task_src/task.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/gen_task_src/task.c.o
.PHONY : gen_task_src/task.c.o

gen_task_src/task.i: gen_task_src/task.c.i
.PHONY : gen_task_src/task.i

# target to preprocess a source file
gen_task_src/task.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/gen_task_src/task.c.i
.PHONY : gen_task_src/task.c.i

gen_task_src/task.s: gen_task_src/task.c.s
.PHONY : gen_task_src/task.s

# target to generate assembly for a file
gen_task_src/task.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/gen_task_src/task.c.s
.PHONY : gen_task_src/task.c.s

gen_task_src/util.o: gen_task_src/util.c.o
.PHONY : gen_task_src/util.o

# target to build an object file
gen_task_src/util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/gen_task_src/util.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/gen_task_src/util.c.o
.PHONY : gen_task_src/util.c.o

gen_task_src/util.i: gen_task_src/util.c.i
.PHONY : gen_task_src/util.i

# target to preprocess a source file
gen_task_src/util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/gen_task_src/util.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/gen_task_src/util.c.i
.PHONY : gen_task_src/util.c.i

gen_task_src/util.s: gen_task_src/util.c.s
.PHONY : gen_task_src/util.s

# target to generate assembly for a file
gen_task_src/util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/gen_task_src/util.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/gen_task_src/util.c.s
.PHONY : gen_task_src/util.c.s

parsers/conf.o: parsers/conf.c.o
.PHONY : parsers/conf.o

# target to build an object file
parsers/conf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/parsers/conf.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/parsers/conf.c.o
.PHONY : parsers/conf.c.o

parsers/conf.i: parsers/conf.c.i
.PHONY : parsers/conf.i

# target to preprocess a source file
parsers/conf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/parsers/conf.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/parsers/conf.c.i
.PHONY : parsers/conf.c.i

parsers/conf.s: parsers/conf.c.s
.PHONY : parsers/conf.s

# target to generate assembly for a file
parsers/conf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/parsers/conf.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/parsers/conf.c.s
.PHONY : parsers/conf.c.s

parsers/conf_gasgen.o: parsers/conf_gasgen.c.o
.PHONY : parsers/conf_gasgen.o

# target to build an object file
parsers/conf_gasgen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/parsers/conf_gasgen.c.o
.PHONY : parsers/conf_gasgen.c.o

parsers/conf_gasgen.i: parsers/conf_gasgen.c.i
.PHONY : parsers/conf_gasgen.i

# target to preprocess a source file
parsers/conf_gasgen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/parsers/conf_gasgen.c.i
.PHONY : parsers/conf_gasgen.c.i

parsers/conf_gasgen.s: parsers/conf_gasgen.c.s
.PHONY : parsers/conf_gasgen.s

# target to generate assembly for a file
parsers/conf_gasgen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/parsers/conf_gasgen.c.s
.PHONY : parsers/conf_gasgen.c.s

parsers/conf_gastask.o: parsers/conf_gastask.c.o
.PHONY : parsers/conf_gastask.o

# target to build an object file
parsers/conf_gastask.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/parsers/conf_gastask.c.o
.PHONY : parsers/conf_gastask.c.o

parsers/conf_gastask.i: parsers/conf_gastask.c.i
.PHONY : parsers/conf_gastask.i

# target to preprocess a source file
parsers/conf_gastask.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/parsers/conf_gastask.c.i
.PHONY : parsers/conf_gastask.c.i

parsers/conf_gastask.s: parsers/conf_gastask.c.s
.PHONY : parsers/conf_gastask.s

# target to generate assembly for a file
parsers/conf_gastask.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/parsers/conf_gastask.c.s
.PHONY : parsers/conf_gastask.c.s

resources/cloud.o: resources/cloud.c.o
.PHONY : resources/cloud.o

# target to build an object file
resources/cloud.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/resources/cloud.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/resources/cloud.c.o
.PHONY : resources/cloud.c.o

resources/cloud.i: resources/cloud.c.i
.PHONY : resources/cloud.i

# target to preprocess a source file
resources/cloud.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/resources/cloud.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/resources/cloud.c.i
.PHONY : resources/cloud.c.i

resources/cloud.s: resources/cloud.c.s
.PHONY : resources/cloud.s

# target to generate assembly for a file
resources/cloud.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/resources/cloud.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/resources/cloud.c.s
.PHONY : resources/cloud.c.s

resources/cpu.o: resources/cpu.c.o
.PHONY : resources/cpu.o

# target to build an object file
resources/cpu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/resources/cpu.c.o
.PHONY : resources/cpu.c.o

resources/cpu.i: resources/cpu.c.i
.PHONY : resources/cpu.i

# target to preprocess a source file
resources/cpu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/resources/cpu.c.i
.PHONY : resources/cpu.c.i

resources/cpu.s: resources/cpu.c.s
.PHONY : resources/cpu.s

# target to generate assembly for a file
resources/cpu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/resources/cpu.c.s
.PHONY : resources/cpu.c.s

resources/mem.o: resources/mem.c.o
.PHONY : resources/mem.o

# target to build an object file
resources/mem.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/resources/mem.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/resources/mem.c.o
.PHONY : resources/mem.c.o

resources/mem.i: resources/mem.c.i
.PHONY : resources/mem.i

# target to preprocess a source file
resources/mem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/resources/mem.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/resources/mem.c.i
.PHONY : resources/mem.c.i

resources/mem.s: resources/mem.c.s
.PHONY : resources/mem.s

# target to generate assembly for a file
resources/mem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/resources/mem.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/resources/mem.c.s
.PHONY : resources/mem.c.s

resources/net_commander.o: resources/net_commander.c.o
.PHONY : resources/net_commander.o

# target to build an object file
resources/net_commander.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/resources/net_commander.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/resources/net_commander.c.o
.PHONY : resources/net_commander.c.o

resources/net_commander.i: resources/net_commander.c.i
.PHONY : resources/net_commander.i

# target to preprocess a source file
resources/net_commander.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/resources/net_commander.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/resources/net_commander.c.i
.PHONY : resources/net_commander.c.i

resources/net_commander.s: resources/net_commander.c.s
.PHONY : resources/net_commander.s

# target to generate assembly for a file
resources/net_commander.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/resources/net_commander.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/resources/net_commander.c.s
.PHONY : resources/net_commander.c.s

resources/network.o: resources/network.c.o
.PHONY : resources/network.o

# target to build an object file
resources/network.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/resources/network.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/resources/network.c.o
.PHONY : resources/network.c.o

resources/network.i: resources/network.c.i
.PHONY : resources/network.i

# target to preprocess a source file
resources/network.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/resources/network.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/resources/network.c.i
.PHONY : resources/network.c.i

resources/network.s: resources/network.c.s
.PHONY : resources/network.s

# target to generate assembly for a file
resources/network.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/resources/network.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/resources/network.c.s
.PHONY : resources/network.c.s

resources/offloadingratio.o: resources/offloadingratio.c.o
.PHONY : resources/offloadingratio.o

# target to build an object file
resources/offloadingratio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/resources/offloadingratio.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/resources/offloadingratio.c.o
.PHONY : resources/offloadingratio.c.o

resources/offloadingratio.i: resources/offloadingratio.c.i
.PHONY : resources/offloadingratio.i

# target to preprocess a source file
resources/offloadingratio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/resources/offloadingratio.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/resources/offloadingratio.c.i
.PHONY : resources/offloadingratio.c.i

resources/offloadingratio.s: resources/offloadingratio.c.s
.PHONY : resources/offloadingratio.s

# target to generate assembly for a file
resources/offloadingratio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gastask.dir/build.make CMakeFiles/gastask.dir/resources/offloadingratio.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gasgen.dir/build.make CMakeFiles/gasgen.dir/resources/offloadingratio.c.s
.PHONY : resources/offloadingratio.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gasgen"
	@echo "... gastask"
	@echo "... dynamic_resource_generators/gen_netcommander.o"
	@echo "... dynamic_resource_generators/gen_netcommander.i"
	@echo "... dynamic_resource_generators/gen_netcommander.s"
	@echo "... dynamic_resource_generators/gen_network.o"
	@echo "... dynamic_resource_generators/gen_network.i"
	@echo "... dynamic_resource_generators/gen_network.s"
	@echo "... dynamic_resource_generators/gen_task.o"
	@echo "... dynamic_resource_generators/gen_task.i"
	@echo "... dynamic_resource_generators/gen_task.s"
	@echo "... gen_task_src/GA.o"
	@echo "... gen_task_src/GA.i"
	@echo "... gen_task_src/GA.s"
	@echo "... gen_task_src/gasgen.o"
	@echo "... gen_task_src/gasgen.i"
	@echo "... gen_task_src/gasgen.s"
	@echo "... gen_task_src/gastask.o"
	@echo "... gen_task_src/gastask.i"
	@echo "... gen_task_src/gastask.s"
	@echo "... gen_task_src/report.o"
	@echo "... gen_task_src/report.i"
	@echo "... gen_task_src/report.s"
	@echo "... gen_task_src/task.o"
	@echo "... gen_task_src/task.i"
	@echo "... gen_task_src/task.s"
	@echo "... gen_task_src/util.o"
	@echo "... gen_task_src/util.i"
	@echo "... gen_task_src/util.s"
	@echo "... parsers/conf.o"
	@echo "... parsers/conf.i"
	@echo "... parsers/conf.s"
	@echo "... parsers/conf_gasgen.o"
	@echo "... parsers/conf_gasgen.i"
	@echo "... parsers/conf_gasgen.s"
	@echo "... parsers/conf_gastask.o"
	@echo "... parsers/conf_gastask.i"
	@echo "... parsers/conf_gastask.s"
	@echo "... resources/cloud.o"
	@echo "... resources/cloud.i"
	@echo "... resources/cloud.s"
	@echo "... resources/cpu.o"
	@echo "... resources/cpu.i"
	@echo "... resources/cpu.s"
	@echo "... resources/mem.o"
	@echo "... resources/mem.i"
	@echo "... resources/mem.s"
	@echo "... resources/net_commander.o"
	@echo "... resources/net_commander.i"
	@echo "... resources/net_commander.s"
	@echo "... resources/network.o"
	@echo "... resources/network.i"
	@echo "... resources/network.s"
	@echo "... resources/offloadingratio.o"
	@echo "... resources/offloadingratio.i"
	@echo "... resources/offloadingratio.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

